Add sample tests

diff --git a/.github/workflows/run-benchmark.yml b/.github/workflows/run-benchmark.yml
--- a/.github/workflows/run-benchmark.yml
+++ b/.github/workflows/run-benchmark.yml
@@ -8,19 +8,13 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-  # Runs the workflow once per day at 3:15am
-  schedule:
-    - cron: '3 16 * * *'
-
 env:
   CACHE_NUMBER: 1  # increase to reset cache manually
+  SNAKEMAKE_PROVENANCE_FILE: metadata4ing_provenance
 
 jobs:
-  tests:
+  run-simulation:
     runs-on: ubuntu-latest
-
-
-
     steps:
       - name: checkout repo content
         uses: actions/checkout@v2
@@ -52,8 +46,16 @@ jobs:
           snakemake --use-conda --force --cores all \
             --reporter metadata4ing \
             --report-metadata4ing-paramscript parameter_extractor.py \
-            --report-metadata4ing-filename metadata4ing_provenance
+            --report-metadata4ing-filename $SNAKEMAKE_PROVENANCE_FILE
       
+      - name: Verify Snakemake provevance output
+        run: |
+          FILE="benchmarks/linear-elastic-plate-with-hole/${SNAKEMAKE_PROVENANCE_FILE}.zip"
+          if [ ! -f "$FILE" ]; then
+            echo "ERROR: Snakemake provevance zip file not found: $FILE"
+            exit 1
+          fi
+
       - name: run_linear-elastic-plate-with-hole-benchmarks_nextflow
         shell: bash -l {0}
         run: |
@@ -65,7 +67,7 @@ jobs:
         with:
             name: snakemake_results_linear-elastic-plate-with-hole
             path: |
-              benchmarks/linear-elastic-plate-with-hole/metadata4ing_provenance.zip
+              benchmarks/linear-elastic-plate-with-hole/${SNAKEMAKE_PROVENANCE_FILE}.zip
 
       - name: Archive Linear Elastic plate with a hole benchmark data for nextflow
         uses: actions/upload-artifact@v4
@@ -76,7 +78,7 @@ jobs:
 
   process-artifacts:
     runs-on: ubuntu-latest
-    needs: tests
+    needs: run-simulation
     steps:
       - name: Checkout repo content
         uses: actions/checkout@v2
@@ -87,10 +89,10 @@ jobs:
           name: snakemake_results_linear-elastic-plate-with-hole
           path: ./artifact_files
 
-      - name: Unzip metadata4ing_provenance.zip
+      - name: Unzip Snakemake Provevnance
         run: |
-          mkdir -p ./metadata4ing_provenance
-          unzip -o ./artifact_files/metadata4ing_provenance.zip -d ./metadata4ing_provenance
+          mkdir -p ./${SNAKEMAKE_PROVENANCE_FILE}
+          unzip -o ./artifact_files/${SNAKEMAKE_PROVENANCE_FILE}.zip -d ./${SNAKEMAKE_PROVENANCE_FILE}
 
       - name: Setup Mambaforge with postprocessing env
         uses: conda-incubator/setup-miniconda@v3
@@ -103,7 +105,7 @@ jobs:
       - name: Run plotting script
         shell: bash -l {0}
         run: |
-          python benchmarks/linear-elastic-plate-with-hole/plot_provenance.py ./metadata4ing_provenance
+          python benchmarks/linear-elastic-plate-with-hole/plot_provenance.py ./${SNAKEMAKE_PROVENANCE_FILE}
 
       - name: Upload PDF plot as artifact
         uses: actions/upload-artifact@v4
